In [1]:
import numpy as np 

In [2]:
#creation of numpy array
x = np.array([1,2,3])
print(x)
print(type(x))  #ndarray

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
print(x.size) # total no. of elements
print(x.shape) #dimensions wise elements 
print(x.ndim) # number of dimensions 

3
(3,)
1


In [4]:
x2d = np.array([[1,2,3],[4,5,6]])
print(x2d)
print(x2d.size) 
print(x2d.shape) 
print(x2d.ndim)

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [5]:
x25 = np.random.randint(1,100,(5,5))
print(x25)

[[74  7 11 64 83]
 [30 29 58 97 65]
 [27 19 87 77  5]
 [69 82  5 55 60]
 [93 64 44 16 32]]


In [6]:
xseql = np.arange(1,101,4) #enhanced version of range()
print(xseql) # 1d matrix
print(xseql.size,"elements")

print(xseql.reshape(5,5)) #1d matrix into 2d

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
25 elements
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [7]:
xseq2 = np.linspace(1,100,50)
print(xseq2.size,"elements")
print('=>1D MATRIX')
print(xseq2)
print("=>1D MATRIX RESHAPED TO 2D")
print(xseq2.reshape(10,5))
print("=>1D MATRIX RESHAPED TO 3D")
print(xseq2.reshape(5,5,2))

50 elements
=>1D MATRIX
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
=>1D MATRIX RESHAPED TO 2D
[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  4

In [8]:
xseq2 = xseq2.reshape(10,5)
print(xseq2)

[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  43.42857143  45.44897959  47.46938776  49.48979592]
 [ 51.51020408  53.53061224  55.55102041  57.57142857  59.59183673]
 [ 61.6122449   63.63265306  65.65306122  67.67346939  69.69387755]
 [ 71.71428571  73.73469388  75.75510204  77.7755102   79.79591837]
 [ 81.81632653  83.83673469  85.85714286  87.87755102  89.89795918]
 [ 91.91836735  93.93877551  95.95918367  97.97959184 100.        ]]


In [9]:
np.ones((5,5), dtype = 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

 - Indexing and Slicing 
 - Boolean Filter
 - Maths and Stats
 - Methods

In [10]:
x25

array([[74,  7, 11, 64, 83],
       [30, 29, 58, 97, 65],
       [27, 19, 87, 77,  5],
       [69, 82,  5, 55, 60],
       [93, 64, 44, 16, 32]])

In [11]:
# first row 
print(x25[0])

[74  7 11 64 83]


In [12]:
#last row 
print(x25[-1])


[93 64 44 16 32]


In [13]:
# single element
print(x25[0,1]) # works same as print(x25[0][1])

7


In [14]:
# 1st column 
print(x25[:,0])

# 2nd column
print(x25[: ,1])

# 3rd column 
print(x25[:, -1])

[74 30 27 69 93]
[ 7 29 19 82 64]
[83 65  5 60 32]


In [15]:
# column 0 and 1 indexs 
print(x25[:,[0,1]])

[[74  7]
 [30 29]
 [27 19]
 [69 82]
 [93 64]]


In [16]:
# column 0,1,2 indexs 
print(x25[:,[0,1]])
# same thing as above 
print(x25[:,:3]) 

[[74  7]
 [30 29]
 [27 19]
 [69 82]
 [93 64]]
[[74  7 11]
 [30 29 58]
 [27 19 87]
 [69 82  5]
 [93 64 44]]


In [17]:
# filtering data without numpy boolean filter (bad idea)
for i in x25:
    for j in i :
        if j <=  20:
            print(j)

7
11
19
5
5
16


In [18]:
x25 <= 20 # boolean filter 

array([[False,  True,  True, False, False],
       [False, False, False, False, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [False, False, False,  True, False]])

In [19]:
x25[x25 <= 20]

array([ 7, 11, 19,  5,  5, 16])

In [20]:
x25[x25 > 50]

array([74, 64, 83, 58, 97, 65, 87, 77, 69, 82, 55, 60, 93, 64])

In [21]:
(x25 > 20) & (x25 < 70)

array([[False, False, False,  True, False],
       [ True,  True,  True, False,  True],
       [ True, False, False, False, False],
       [ True, False, False,  True,  True],
       [False,  True,  True, False,  True]])

In [22]:
x25[(x25 > 20) & (x25 < 70)]

array([64, 30, 29, 58, 65, 27, 69, 55, 60, 64, 44, 32])

In [23]:
np.append(x25,[1,2,3,4,5]) # not as exoected , but works

array([74,  7, 11, 64, 83, 30, 29, 58, 97, 65, 27, 19, 87, 77,  5, 69, 82,
        5, 55, 60, 93, 64, 44, 16, 32,  1,  2,  3,  4,  5])

In [24]:
np.append(x25 , np.array([[1,2,3,4,5]]), axis=0)


array([[74,  7, 11, 64, 83],
       [30, 29, 58, 97, 65],
       [27, 19, 87, 77,  5],
       [69, 82,  5, 55, 60],
       [93, 64, 44, 16, 32],
       [ 1,  2,  3,  4,  5]])

In [25]:
a = np.random.randint(1,100,(3,2))
b = np.random.randint(1,100,(2,3))

In [26]:
print(a.shape)
print(b.shape)

(3, 2)
(2, 3)


In [27]:
a.T # same as transpose of matrix

array([[58, 86, 35],
       [52, 77, 18]])

In [28]:
print(np.hstack((a,b.T)))

[[58 52 31 60]
 [86 77 20  2]
 [35 18 33 22]]


In [29]:
print(np.hstack((a.T,b)))

[[58 86 35 31 20 33]
 [52 77 18 60  2 22]]


In [30]:
print(np.vstack((a,b.T)))
print(np.vstack((a.T,b)))

[[58 52]
 [86 77]
 [35 18]
 [31 60]
 [20  2]
 [33 22]]
[[58 86 35]
 [52 77 18]
 [31 20 33]
 [60  2 22]]
